// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeYTynHWMKIs7SyWcxBmU8wyNjOAiE38s',
    appId: '1:868698601721:android:9a3e747a51e2e49f854a28',
    messagingSenderId: '868698601721',
    projectId: 'bankapp-9798a',
    storageBucket: 'bankapp-9798a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsLBXT0eKg7rkLh0BEgM7MISekruyLwlY',
    appId: '1:868698601721:ios:c34c3cf2b97ba595854a28',
    messagingSenderId: '868698601721',
    projectId: 'bankapp-9798a',
    storageBucket: 'bankapp-9798a.appspot.com',
    androidClientId: '868698601721-6b169hh5mo0lc70cd6915cn3u5hiuna7.apps.googleusercontent.com',
    iosClientId: '868698601721-ru460rd9vim48utkrkmhtp64n1il6bhl.apps.googleusercontent.com',
    iosBundleId: 'com.theholylabs.grape',
  );

}